INSERT INTO `TeddyBear` VALUES('', 'angry-face.png', 'Angry Face ', ':angry-face:');
INSERT INTO `TeddyBear` VALUES('', 'anguished-face.png', 'Anguished Face ', ':anguished-face:');
INSERT INTO `TeddyBear` VALUES('', 'confused-face.png', 'Confused Face ', ':confused-face:');
INSERT INTO `TeddyBear` VALUES('', 'crying-face.png', 'Crying Face ', ':crying-face:');
INSERT INTO `TeddyBear` VALUES('', 'disappointed-face.png', 'Disappointed Face ', ':disappointed-face:');
INSERT INTO `TeddyBear` VALUES('', 'expressionless-face.png', 'Expressionless Face ', ':expressionless-face:');
INSERT INTO `TeddyBear` VALUES('', 'face-savouring-delicious-food.png', 'Face Savouring Delicious Food ', ':face-savouring-delicious-food:');
INSERT INTO `TeddyBear` VALUES('', 'face-screaming-in-fear.png', 'Face Screaming In Fear ', ':face-screaming-in-fear:');
INSERT INTO `TeddyBear` VALUES('', 'face-throwing-a-kiss.png', 'Face Throwing A Kiss ', ':face-throwing-a-kiss:');
INSERT INTO `TeddyBear` VALUES('', 'face-with-cold-sweat.png', 'Face With Cold Sweat ', ':face-with-cold-sweat:');
INSERT INTO `TeddyBear` VALUES('', 'face-with-look-of-triumph.png', 'Face With Look Of Triumph ', ':face-with-look-of-triumph:');
INSERT INTO `TeddyBear` VALUES('', 'face-with-open-mouth-and-cold-sweat.png', 'Face With Open Mouth And Cold Sweat ', ':face-with-open-mouth-and-cold-sweat:');
INSERT INTO `TeddyBear` VALUES('', 'face-with-open-mouth.png', 'Face With Open Mouth ', ':face-with-open-mouth:');
INSERT INTO `TeddyBear` VALUES('', 'face-with-stuck-out-tongue.png', 'Face With Stuck Out Tongue ', ':face-with-stuck-out-tongue:');
INSERT INTO `TeddyBear` VALUES('', 'face-with-tears-of-joy.png', 'Face With Tears Of Joy ', ':face-with-tears-of-joy:');
INSERT INTO `TeddyBear` VALUES('', 'fearful-face.png', 'Fearful Face ', ':fearful-face:');
INSERT INTO `TeddyBear` VALUES('', 'frowning-face-with-open-mouth.png', 'Frowning Face With Open Mouth ', ':frowning-face-with-open-mouth:');
INSERT INTO `TeddyBear` VALUES('', 'grimacing-face.png', 'Grimacing Face ', ':grimacing-face:');
INSERT INTO `TeddyBear` VALUES('', 'grinning-face-with-smiling-eyes.png', 'Grinning Face With Smiling Eyes ', ':grinning-face-with-smiling-eyes:');
INSERT INTO `TeddyBear` VALUES('', 'grinning-face.png', 'Grinning Face ', ':grinning-face:');
INSERT INTO `TeddyBear` VALUES('', 'hushed-face.png', 'Hushed Face ', ':hushed-face:');
INSERT INTO `TeddyBear` VALUES('', 'loudly-crying-face.png', 'Loudly Crying Face ', ':loudly-crying-face:');
INSERT INTO `TeddyBear` VALUES('', 'neutral-face.png', 'Neutral Face ', ':neutral-face:');
INSERT INTO `TeddyBear` VALUES('', 'persevering-face.png', 'Persevering Face ', ':persevering-face:');
INSERT INTO `TeddyBear` VALUES('', 'pouting-face.png', 'Pouting Face ', ':pouting-face:');
INSERT INTO `TeddyBear` VALUES('', 'relieved-face.png', 'Relieved Face ', ':relieved-face:');
INSERT INTO `TeddyBear` VALUES('', 'sleeping-face.png', 'Sleeping Face ', ':sleeping-face:');
INSERT INTO `TeddyBear` VALUES('', 'sleepy-face.png', 'Sleepy Face ', ':sleepy-face:');
INSERT INTO `TeddyBear` VALUES('', 'slightly-frowning-face.png', 'Slightly Frowning Face ', ':slightly-frowning-face:');
INSERT INTO `TeddyBear` VALUES('', 'smiling-face-with-halo.png', 'Smiling Face With Halo ', ':smiling-face-with-halo:');
INSERT INTO `TeddyBear` VALUES('', 'smiling-face-with-heart-shaped-eyes.png', 'Smiling Face With Heart Shaped Eyes ', ':smiling-face-with-heart-shaped-eyes:');
INSERT INTO `TeddyBear` VALUES('', 'smiling-face-with-open-mouth-and-cold-sweat.png', 'Smiling Face With Open Mouth And Cold Sweat ', ':smiling-face-with-open-mouth-and-cold-sweat:');
INSERT INTO `TeddyBear` VALUES('', 'smiling-face-with-open-mouth-and-smiling-eyes.png', 'Smiling Face With Open Mouth And Smiling Eyes ', ':smiling-face-with-open-mouth-and-smiling-eyes:');
INSERT INTO `TeddyBear` VALUES('', 'smiling-face-with-open-mouth-and-tightly-closed-eyes.png', 'Smiling Face With Open Mouth And Tightly Closed Eyes ', ':smiling-face-with-open-mouth-and-tightly-closed-eyes:');
INSERT INTO `TeddyBear` VALUES('', 'smiling-face-with-open-mouth.png', 'Smiling Face With Open Mouth ', ':smiling-face-with-open-mouth:');
INSERT INTO `TeddyBear` VALUES('', 'smiling-face-with-smiling-eyes.png', 'Smiling Face With Smiling Eyes ', ':smiling-face-with-smiling-eyes:');
INSERT INTO `TeddyBear` VALUES('', 'smiling-face-with-sunglasses.png', 'Smiling Face With Sunglasses ', ':smiling-face-with-sunglasses:');
INSERT INTO `TeddyBear` VALUES('', 'smirking-face.png', 'Smirking Face ', ':smirking-face:');
INSERT INTO `TeddyBear` VALUES('', 'tired-face.png', 'Tired Face ', ':tired-face:');
INSERT INTO `TeddyBear` VALUES('', 'white-smiling-face.png', 'White Smiling Face ', ':white-smiling-face:');
INSERT INTO `TeddyBear` VALUES('', 'winking-face.png', 'Winking Face ', ':winking-face:');
INSERT INTO `TeddyBear` VALUES('', 'worried-face.png', 'Worried Face ', ':worried-face:');
