CREATE TABLE IF NOT EXISTS `TeddyBear` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `image_url` varchar(256) NOT NULL,
  `title` varchar(256) NOT NULL,
  `smilie_text` varchar(256) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=43 ;

INSERT INTO `TeddyBear` (`id`, `image_url`, `title`, `smilie_text`) VALUES
(1, 'angry-face.png', 'Angry Face', ':angry-face:'),
(2, 'anguished-face.png', 'Anguished Face', ':anguished-face:'),
(3, 'confused-face.png', 'Confused Face', ':confused-face:'),
(4, 'crying-face.png', 'Crying Face', ':crying-face:'),
(5, 'disappointed-face.png', 'Disappointed Face', ':disappointed-face:'),
(6, 'expressionless-face.png', 'Expressionless Face', ':expressionless-face:'),
(7, 'face-savouring-delicious-food.png', 'Face Savouring Delicious Food', ':face-savouring-delicious-food:'),
(8, 'face-screaming-in-fear.png', 'Face Screaming In Fear', ':face-screaming-in-fear:'),
(9, 'face-throwing-a-kiss.png', 'Face Throwing A Kiss', ':face-throwing-a-kiss:'),
(10, 'face-with-cold-sweat.png', 'Face With Cold Sweat', ':face-with-cold-sweat:'),
(11, 'face-with-look-of-triumph.png', 'Face With Look Of Triumph', ':face-with-look-of-triumph:'),
(12, 'face-with-open-mouth-and-cold-sweat.png', 'Face With Open Mouth And Cold Sweat', ':face-with-open-mouth-and-cold-sweat:'),
(13, 'face-with-open-mouth.png', 'Face With Open Mouth', ':face-with-open-mouth:'),
(14, 'face-with-stuck-out-tongue.png', 'Face With Stuck Out Tongue', ':face-with-stuck-out-tongue:'),
(15, 'face-with-tears-of-joy.png', 'Face With Tears Of Joy', ':face-with-tears-of-joy:'),
(16, 'fearful-face.png', 'Fearful Face', ':fearful-face:'),
(17, 'frowning-face-with-open-mouth.png', 'Frowning Face With Open Mouth', ':frowning-face-with-open-mouth:'),
(18, 'grimacing-face.png', 'Grimacing Face', ':grimacing-face:'),
(19, 'grinning-face-with-smiling-eyes.png', 'Grinning Face With Smiling Eyes', ':grinning-face-with-smiling-eyes:'),
(20, 'grinning-face.png', 'Grinning Face', ':grinning-face:'),
(21, 'hushed-face.png', 'Hushed Face', ':hushed-face:'),
(22, 'loudly-crying-face.png', 'Loudly Crying Face', ':loudly-crying-face:'),
(23, 'neutral-face.png', 'Neutral Face', ':neutral-face:'),
(24, 'persevering-face.png', 'Persevering Face', ':persevering-face:'),
(25, 'pouting-face.png', 'Pouting Face', ':pouting-face:'),
(26, 'relieved-face.png', 'Relieved Face', ':relieved-face:'),
(27, 'sleeping-face.png', 'Sleeping Face', ':sleeping-face:'),
(28, 'sleepy-face.png', 'Sleepy Face', ':sleepy-face:'),
(29, 'slightly-frowning-face.png', 'Slightly Frowning Face', ':slightly-frowning-face:'),
(30, 'smiling-face-with-halo.png', 'Smiling Face With Halo', ':smiling-face-with-halo:'),
(31, 'smiling-face-with-heart-shaped-eyes.png', 'Smiling Face With Heart Shaped Eyes', ':smiling-face-with-heart-shaped-eyes:'),
(32, 'smiling-face-with-open-mouth-and-cold-sweat.png', 'Smiling Face With Open Mouth And Cold Sweat', ':smiling-face-with-open-mouth-and-cold-sweat:'),
(33, 'smiling-face-with-open-mouth-and-smiling-eyes.png', 'Smiling Face With Open Mouth And Smiling Eyes', ':smiling-face-with-open-mouth-and-smiling-eyes:'),
(34, 'smiling-face-with-open-mouth-and-tightly-closed-eyes.png', 'Smiling Face With Open Mouth And Tightly Closed Eyes', ':smiling-face-with-open-mouth-and-tightly-closed-eyes:'),
(35, 'smiling-face-with-open-mouth.png', 'Smiling Face With Open Mouth', ':smiling-face-with-open-mouth:'),
(36, 'smiling-face-with-smiling-eyes.png', 'Smiling Face With Smiling Eyes', ':smiling-face-with-smiling-eyes:'),
(37, 'smiling-face-with-sunglasses.png', 'Smiling Face With Sunglasses', ':smiling-face-with-sunglasses:'),
(38, 'smirking-face.png', 'Smirking Face', ':smirking-face:'),
(39, 'tired-face.png', 'Tired Face', ':tired-face:'),
(40, 'white-smiling-face.png', 'White Smiling Face', ':white-smiling-face:'),
(41, 'winking-face.png', 'Winking Face', ':winking-face:'),
(42, 'worried-face.png', 'Worried Face', ':worried-face:');